app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about-us/', views.AboutView.as_view(), name='aboutView'),
	path('contact/', views.ContactView.as_view(), name='contactView'),
	path('faqs/', views.FaqView.as_view(), name='faqView'),
    path('products/', include('products.urls')),
    path('account/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "House Of Faith"
admin.site.site_title  = "House Of Faith Admin Portal"

products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('add-to-wishlist/', views.addToWishlist.as_view(), name='addToWishlist'),
    path('get-product/', views.getProduct.as_view(), name='getProduct'),
    path('add-to-cart/', views.addToCart.as_view(), name='addToCart'),
    path('remove-from-cart/', views.removeFromCart.as_view(), name='removeFromCart'),
    path('place-order/', views.placeOrder.as_view(), name='placeOrder'),
    path('detail/<str:product_slug>/', views.ProductDetail.as_view(), name='productDetailView'),
    path('<str:category_slug>/', views.ProductView.as_view(), name='productView'),
    path('<str:category_slug>/<str:sub_category_slug>/', views.ProductView.as_view(), name='productView'),
    path('<str:category_slug>/<str:sub_category_slug>/<str:sub_sub_category_slug>/', views.ProductView.as_view(), name='productView'),
]

products/forms.py
from django import forms
from .models import (
	Products, 
	Product_Image, 
	Product_Available_Stock, 
	Product_Wise_Offer,
)


class ProductForm(forms.ModelForm):
	class Meta:
		model = Products
		fields = ['title', 'product_category', 'status', 'description']


class ProductImageForm(forms.ModelForm):
	class Meta:
		model = Product_Image
		fields = ['product', 'image_path']


class ProductStockForm(forms.ModelForm):
	class Meta:
		model = Product_Available_Stock
		fields = ['product', 'product_category', 'product_sub_category', 'product_sub_sub_category', 'quantity', 'unit_price', 'total_price']


class ProductWiseOfferForm(forms.ModelForm):
	class Meta:
		model = Product_Wise_Offer
		fields = ['product_offer', 'amount']

products/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from django.conf import settings
from django.core.mail import send_mail

from app_libs.file_upload import FileUpload
from products.forms import ProductForm

from app_libs.dump import dd
from accounts.models import User
from .models import (
    Products,
    Product_Image,
    Product_Categories, Product_Sub_Categories, Product_Sub_Sub_Categories, Product_Wise_Size, Product_Size,
    Product_Wise_Color, Product_Color, Product_Available_Stock, Order, OrderItem, ShippingAddress,
)


class ProductView(View):
    def get(self, request, category_slug='', sub_category_slug='', sub_sub_category_slug=''):
        data = {}

        data['page_title'] = category_slug.replace('-', ' ').capitalize() +' | '+ 'House Of Faith'
        if sub_category_slug:
            data['page_title'] = sub_category_slug.replace('-', ' ').capitalize() +' - '+ data['page_title']
            if sub_sub_category_slug:
                data['page_title'] = sub_sub_category_slug.replace('-', ' ').capitalize() +' - '+ data['page_title']

        data['menu_title_c'] = category_slug.replace('-', ' ').capitalize()
        data['menu_title_sc'] = sub_category_slug.replace('-', ' ').capitalize()
        data['menu_title_ssc'] = sub_sub_category_slug.replace('-', ' ').capitalize()

        request.session['category_slug'] = category_slug
        request.session['sub_category_slug'] = sub_category_slug
        request.session['sub_sub_category_slug'] = sub_sub_category_slug

        # pagination
        product_list = Products.objects.get_categorical_product(category_slug, sub_category_slug, sub_sub_category_slug)
        page = request.GET.get('page', 1)

        # dump_data = dd(request, product_list)
        # dump_data = dd(request, product_list[0].stock_product.all())
        # dump_data = dd(request, product_list[0].product_offer.all())
        # return HttpResponse(dump_data)

        # number of product per page
        paginator = Paginator(product_list, 15)
        try:
            data['products'] = paginator.page(page)
        except PageNotAnInteger:
            data['products'] = paginator.page(1)
        except EmptyPage:
            data['products'] = paginator.page(paginator.num_pages)
        # end of pagination

        template = 'products/collections.html'

        return render(request, template, data)


class ProductDetail(View):
    def get(self, request, product_slug):
        data = {}
        data['products'] = Products.objects.get_all_product()
        data['product_detail'] = Products.objects.get_product_detail(product_slug)
        template = 'products/product.html'

        # dump_data = dd(request, data['product_detail'])
        # dump_data = dd(request, data['product_detail'].stock_product.all())
        # dump_data = dd(request, data['product_detail'].product_wise_size.all())
        # return HttpResponse(dump_data)

        return render(request, template, data)


class addToCart(View):
    def get(self, request):
        data = {}
        data['page_title'] = 'cart'

        device = request.COOKIES['device']
        customer = User.objects.get_user(device=device)
        if request.user.is_authenticated:
            customer = User.objects.get_user(id=request.user.id)

        # get customer orders
        data['orders'] = Order.objects.get_order(customer=customer)

        # dump_data = dd(request, data['orders'].order_item.all())
        # return HttpResponse(dump_data)

        template = 'products/cart.html'
        return render(request, template, data)

    def post(self, request):
        user_id = request.POST.get('user_id')
        product_id = request.POST.get('product_id')
        quantity = request.POST.get('quantity')

        if user_id:
            customer = User.objects.get(id=user_id)
        else:
            device = request.COOKIES['device']
            customer, created = User.objects.get_or_create(device=device)

        product = Products.objects.get_product(id=product_id)
        unit_price = Product_Available_Stock.objects.get_product_unit_price(product_id=product_id)

        # create order
        order, created = Order.objects.get_or_create(customer=customer, is_complete=False)

        data = {}
        data['order'] = order
        data['product'] = product
        data['quantity'] = quantity
        data['unit_price'] = unit_price

        # create order item
        order_item = OrderItem.objects.save(data=data)

        if order_item:
            return HttpResponse(True)
        return HttpResponse(False)


class removeFromCart(View):
    def get(self, request):
        order_item_id = request.GET.get('order_item_id')
        delete_order_item = OrderItem.objects.delete(id=order_item_id)
        return HttpResponse(delete_order_item)


class placeOrder(View):
    def post(self, request):
        order_id = request.POST.get('order_id')
        product_ids = request.POST.getlist('product_id[]')
        quantities = request.POST.getlist('quantity[]')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        alternative_phone = request.POST.get('alternative_phone')
        address = request.POST.get('address')
        remarks = request.POST.get('remarks')

        if request.user.is_authenticated:
            customer = User.objects.get_user(id=request.user.id)
        else:
            device = request.COOKIES['device']
            customer = User.objects.get_user(device=device)

        order = Order.objects.get_order(customer=customer)

        data = {}
        data['email'] = email
        data['mobile_number'] = phone
        data['alternative_mobile_number'] = alternative_phone
        data['address'] = address
        data['remarks'] = remarks
        data['customer'] = customer
        data['order'] = order

        # subject = 'Order place receipt from House of faith'
        # message = f'Hi {email}, thank you for placing order in House of faith. Your order will be on your door soon.'
        # email_from = settings.EMAIL_HOST_USER
        # recipient_list = [email, ]
        # send_mail_status = send_mail(subject, message, email_from, recipient_list)
        #
        # if send_mail_status:
        #     # create place order
        #     _ = ShippingAddress.objects.save(data=data)
        #     _ = Order.objects.update_order_status(customer=customer)
        #     for key, value in enumerate(quantities):
        #         _ = OrderItem.objects.update_quantity(order_id=order_id, product_id=product_ids[key], quantity=quantities[key])
        #     messages.success(request, 'You placed order successfully!!')
        #     return redirect('/products/add-to-cart/')

        # create place order
        set_shipping_address = ShippingAddress.objects.save(data=data)
        if set_shipping_address:
            _ = Order.objects.update_order_status(id=order_id)
            for key, value in enumerate(quantities):
                _ = OrderItem.objects.update_quantity(order_id=order_id, product_id=product_ids[key], quantity=quantities[key])
            messages.success(request, 'You placed order successfully!!')
            return redirect('/products/add-to-cart/')

        messages.error(request, 'Some error occurred!!')
        return redirect('/products/add-to-cart/')


class addToWishlist(View):
    def post(self, request):
        product_slug = request.POST.get('product_slug')
        product = Products.objects.get_product_detail(product_slug)
        product_images = product.product_image.all()
        product_wise_sizes = product.product_wise_size.all()
        product_stock = product.stock_product.all()

        # dump_data = dd(request, product)
        # dump_data = dd(request, product_images)
        # return HttpResponse(dump_data)

        # product = serializers.serialize('json', [product])
        # return JsonResponse(product, safe=False)

        html = '<div class="modal-note wishlist-note">Added to <a href="wish-list.html">Wishlist</a></div>'
        html += '<div class="modal-body-inner">'
        html += '<div class="modal-left wishlist-left">'
        html += '<div class="modal-product wishlist-product">'
        html += '<div class="product-left">'
        html += '<div class="wishlist-image modal-image wishlist-image-213223800871">'
        html += '<img src="'+product_images[0].image_path+'" alt="product image">'
        html += '</div>'
        html += '</div>'
        html += '</div>'
        html += '</div>'
        html += '<div class="modal-right wishlist-right">'
        html += '<div class="wishlist-cart">'
        html += '<form action="#" method="post" class="variants-form variants"  enctype="multipart/form-data">'
        html += '<div class="form-left">'
        html += '<div class="product-right">'
        html += '<div class="name wishlist-name"><a href="">'+product.title+'</a></div>'
        if product.product_offer.all():
            html += '<div class="wishlist-price wishlist-price-213223800871"><span class="price"><span class="money" data-currency-usd="'+str(product_stock[0].after_offer_unit_price)+'" data-currency="BDT">৳ '+str(product_stock[0].after_offer_unit_price)+'</span></span>'
        else:
            html += '<div class="wishlist-price wishlist-price-213223800871"><span class="price"><span class="money" data-currency-usd="'+str(product_stock[0].unit_price)+'" data-currency="BDT">৳ '+str(product_stock[0].unit_price)+'</span></span>'
        html += '</div>'
        html += '</div>'
        html += '<div class="quantity-content">'
        html += '<label>QTY</label>'
        html += '<input type="hidden" id="max-quantity" value="'+str(product_stock[0].quantity)+'">'

products/templates/products/cart.html
{% extends "base.html" %}
{% load static %}
{% load filters %}

{% block body %}

{% if messages %}
  {% for msg in messages %}
  <div class="alert {{msg.level_tag}} alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {{msg.message}}
  </div>
  {% endfor %}
{% endif %}

<!-- Main Content -->
<div class="page-container" id="PageContainer">
  <main class="main-content" id="MainContent" role="main">
    <section class="heading-content">
      <div class="heading-wrapper">
        <div class="container">
          <div class="row">
            <div class="page-heading-inner heading-group">
              <div class="breadcrumb-group">
                <h1 class="hidden">Your Cart</h1>
                <div class="breadcrumb clearfix">
                  <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="index-2.html" title="Fast Food" itemprop="url"><span itemprop="title"><i class="fa fa-home"></i></span></a>
                </span>
                <span class="arrow-space"></span>
                <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
                  <a href="cart.html" title="Your Cart" itemprop="url"><span itemprop="title">Your Cart</span></a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="cart-content">
    <div class="cart-wrapper">
      <div class="container">
        <div class="row">
          <div id="shopify-section-cart-template" class="shopify-section">
            <div class="cart-inner">
              <div id="cart">
                <div class="cart-form">
                  <form action="{% url 'products:placeOrder' %}" method="post" id="cartform">
                    {% csrf_token %}
                    <input type="hidden" size="4" name="order_id" value="{{ orders.id }}">
                    <table>
                      <thead>
                        <tr>
                          <th class="image" colspan="2">Product</th>
                          <th class="price">Price</th>
                          <th class="qty">Quantity</th>
                          <th class="total">Total</th>
                          <th class="remove">Remove</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for order_item in orders.order_item.all %}
                        <tr>
                          <td class="image">
                            <div class="product_image">
                              <a href="product.html">
                                {{ order_item.product.id|get_product_image }}
                              </a>
                            </div>
                          </td>
                          <td class="image-info">
                            <div class="product_name">
                              <a href="product.html">
                                {{ order_item.product.title }}
                              </a>
                              <div class="group_mobile">
                                <span class="price-mobile"><span class="money" data-currency-usd="$20.00">{{ order_item.unit_price }}</span></span>
                                <div class="quantity-mobile">
                                  <div class="quantity-wrapper">
                                    <div class="wrapper">
                                      <span class="quantity-title">Quantity</span>
                                      <input type="text" size="4" value="1" class="tc item-quantity-mobile">
                                    </div>
                                    <!--End wrapper-->
                                  </div>
                                </div>
                              </div>
                              <div class="group_mobile">
                                <div class="remove-mobile">
                                  <a href="#" class="cart"><span class="lnr lnr-trash"></span></a>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="price"><span class="money" data-currency-usd="$20.00">{{ order_item.unit_price }}</span></td>
                          <td class="qty">
                            <div class="quantity-wrapper">
                              <div class="wrapper">
                                <input type="hidden" size="4" name="product_id[]" value="{{ order_item.product.id }}">
                                <input type="text" size="4" name="quantity[]" value="{{ order_item.quantity }}" onchange="calculateTotal($(this))" class="tc item-quantity">
                              </div>
                              <!--End wrapper-->
                            </div>
                            <!--End quantily wrapper-->
                          </td>
                          <td class="total title-1"><span class="money item-total-price" data-currency-usd="$20.00">{{ order_item.get_total }}</span></td>
                          <td class="remove"><a href="#" class="cart" onclick="removeFromCart($(this), {{ order_item.id }})"><span class="lnr lnr-trash"></span></a></td>
                        </tr>
                        {% endfor %}
                        <tr class="summary">
                          <td class="total_label" colspan="5">Subtotal</td>
                          <td class="price" colspan="1"><span class="total"><strong><span class="money" data-currency-usd="$90.00" id="total"></span></strong>
                          </span>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  <div class="group-button">
                    <a href="{% url 'home' %}" class="_btn">Continue Shopping</a>
                    <div class="group_btn_right">
                      <input type="button" class="_btn clearAllCart" value="Clear all">
                    </div>
                  </div>
                  <div class="group-checkout-input">
                    <div class="shipping-calculator col-sm-6 col-xs-12 ">
                      <div id="shipping-calculator">
                        <h3>Get shipping estimates</h3>
                        <div class="group_form">
                          <div class="form-item">
                            <label for="email">Email Address</label>
                            <input type="email" id="email" name="email" required>
                          </div>
                          <div class="form-item">
                            <label for="phone">Phone No.</label>
                            <input type="text" id="phone" name="phone" required>
                          </div>
                          <div class="form-item">
                            <label for="alternative_phone">Alternative Phone No.</label>
                            <input type="text" id="alternative_phone" name="alternative_phone" required>
                          </div>
                          <div class="form-item">
                            <label for="address">Delivery Address</label>
                            <textarea id="address" name="address" placeholder="Enter your place order address here..." required></textarea>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="checkout-buttons col-sm-6 col-xs-12">
                      <div class="note-content group_form">
                        <div class="form-item">
                          <label for="remarks">Add special instructions for your order</label>
                          <textarea id="remarks" name="remarks" placeholder="Enter text here..."></textarea>
                        </div>
                      </div>
                      <div class="checkout-content">
                        <div class="buttons clearfix">
                          <input type="submit" id="checkout" class="_btn" name="checkout" value="Check Out">
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
          <script>
          $(window).ready(function($) {
            $(".quantity-mobile input").change(function() {
              var qty = $(this).val();
              $(this).parents('tr').find('.item-quantity').val(qty);
            });
          });

          $(document).ready(function () {
            calculateGrandTotal();
          });

          function calculateGrandTotal()
          {
            // the value of sum needs to be reset for each row, so it has to be set inside the row loop
            var sum = 0
            // iterate through each row in the table
            $('tr').each(function () {
                // find the item-total-price elements in the current row and sum it
                var money = $(this).find('.item-total-price').text();
                if (!isNaN(money) && money.length !== 0) {
                  sum += parseFloat(money);
                }
            });
            // set the value of currents rows sum to the item-total-price element in the current row
            $('#total').html(sum);
          }

          function removeFromCart(item, order_item_id)
          {
             var url = "{% url 'products:removeFromCart' %}";
             var data = {
              order_item_id: order_item_id
            }

            $.get(url, data, function(response) {
                item.closest('tr').remove();
                calculateGrandTotal();
            });
          }

          function calculateTotal(item)
          {
            var quantity = item.val();
            var price = item.closest('tr').find('.price').text();
            var total_price = quantity * price;
            item.closest('tr').find('.item-total-price').html(total_price);

            calculateGrandTotal();
          }
          </script>
        </div>
      </div>
    </div>
  </div>
</section>
</main>
</div>
{% endblock %}

products/templates/products/left_sidebar.html
{% load static %}

<style type="text/css">
	.list-group-item {
		background-color: #F2E6DC;
	}

	.custom-active {
		color: #AD3B39;
	}
</style>

<div class="collection-leftsidebar sidebar col-sm-3 clearfix">
	<div class="collection-leftsidebar-group">

		<div class="sidebar-block collection-block">
			<h3 class="sidebar-title">
				<span class="text">Categories</span>
				<span class="cs-icon icon-minus"></span>
			</h3>
			<div class="sidebar-content">
				<ul class="list-cat">
					{% for category in categories %}
					<li class="{{ category.slug }}">
						<div class="row">
							<div class="col-sm-10">
								<a href="{% url 'products:productView' category.slug %}">{{ category.name }}</a>
							</div>
							<div class="col-sm-2">
								<span class="cs-icon icon-plus" data-toggle="collapse" data-target="#{{ forloop.counter }}" onclick="categoryToggle($(this))"></span>
							</div>
						</div>
						<ul class="list-cat collapse" id="{{ forloop.counter }}">
							{% for sub_category in category.product_sub_category.all %}
							<li class="{{ sub_category.slug }}">
								<div class="row">
									<div class="col-sm-10">
										<a href="{% url 'products:productView' category.slug sub_category.slug %}">{{ sub_category.name }}</a>
									</div>
									<div class="col-sm-2">
										<span class="cs-icon icon-plus" data-toggle="collapse" data-target="#{{ forloop.parentloop.counter }}-{{ forloop.counter }}" onclick="categoryToggle($(this))"></span>
									</div>
								</div>
								<ul class="list-cat collapse" id="{{ forloop.parentloop.counter }}-{{ forloop.counter }}">
									{% for sub_sub_category in sub_category.product_sub_sub_category.all %}
									<li class="{{ sub_sub_category.slug }}">
										<a href="{% url 'products:productView' category.slug sub_category.slug sub_sub_category.slug %}">{{ sub_sub_category.name }}</a>
									</li>
									{% endfor %}
								</ul>
							</li>
							{% endfor %}
						</ul>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="sidebar-block latest-block">
			<h3 class="sidebar-title">
				<span class="text">LATEST</span>
				<span class="cs-icon icon-minus"></span>
			</h3>
			<div class="sidebar-content">
				<div class="latest-inner">

					{% for product in latest_products %}
					{% if product.status == True %}
					<div class="products-item">
						<div class="row-container product-circle">
							<div class="product home_product">
								<div class="row-left">
									<a href="{% url 'products:productDetailView' product.slug %}" class="container_item">
										<div class="hoverBorderWrapper">
											<img src="{{ product.product_image.first.image_path }}" class="not-rotation img-responsive front" alt="Coke">
											<div class="mask"></div>
										</div>
									</a>
								</div>
								<div class="row-right">
									<div class="product-title"><a class="title-5" href="{% url 'products:productDetailView' product.slug %}">{{ product.title }}</a></div>
									<div class="rating-star">
										<span class="spr-badge" data-rating="5.0">
											<span class="spr-starrating spr-badge-starrating">
												<i class="spr-icon spr-icon-star" style=""></i>
												<i class="spr-icon spr-icon-star" style=""></i>
												<i class="spr-icon spr-icon-star" style=""></i>
												<i class="spr-icon spr-icon-star" style=""></i>
												<i class="spr-icon spr-icon-star" style=""></i>
											</span>
											<span class="spr-badge-caption">1 review</span>
										</span>
									</div>
									<div class="product-price">
										{% if product.product_offer.all %}
										<span class="price_sale">
											<span class="money" data-currency-usd="{{ product.stock_product.first.after_offer_unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.after_offer_unit_price }}</span>
										</span>
										<del class="price_compare">
											<span class="money" data-currency-usd="{{ product.stock_product.first.unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.unit_price }}</span>
										</del>
										{% else %}
										<span class="price_sale">
											<span class="money" data-currency-usd="{{ product.stock_product.first.unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.unit_price }}</span>
										</span>
										{% endif %}
									</div>
								</div>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}

				</div>
			</div>
		</div>

		<!-- filter tags group -->
		<div class="sidebar-block filter-block">
			<h3 class="sidebar-title">
				<span class="text">Size</span>
				<span class="cs-icon icon-minus"></span>
			</h3>
			<div class="sidebar-content">
				<ul class="filter-content ">
					{% for size in sizes %}
					<li data-handle="{{ size.name }}">
						<a href="#" title="Narrow selection to products matching tag {{ size.name }}">
							<span class="fe-checkbox"></span>{{ size.name }}
						</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="sidebar-block filter-block">
			<h3 class="sidebar-title">
				<span class="text">Price</span>
				<span class="cs-icon icon-minus"></span>
			</h3>
			<div class="sidebar-content">
				<ul class="filter-content ">
					<li data-handle="under-100">
						<a href="#" title="Narrow selection to products matching tag Under $100">
							<span class="fe-checkbox"></span>Under $100
						</a>
					</li>
					<li data-handle="100-200">
						<a href="#" title="Narrow selection to products matching tag $100 - $200">
							<span class="fe-checkbox"></span>$100 - $200
						</a>
					</li>
					<li data-handle="above-200">
						<a href="#" title="Narrow selection to products matching tag Above $200">
							<span class="fe-checkbox"></span>Above $200
						</a>
					</li>
				</ul>
			</div>
		</div>

	</div>
</div>

<div class="hidden">
	<input type="hidden" id="category" value="{{ request.session.category_slug }}">
	<input type="hidden" id="sub-category" value="{{ request.session.sub_category_slug }}">
	<input type="hidden" id="sub-sub-category" value="{{ request.session.sub_sub_category_slug }}">
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">

	$(function() {
		var category = '';
		var sub_category = '';
		var sub_sub_category = '';

		category = $('#category').val();
		sub_category = $('#sub-category').val();
		sub_sub_category = $('#sub-sub-category').val();

		if(category) {
			$('.'+category).find('a:first').css('color', '#AD3B39');
		}

		if(sub_category) {
			$('.'+sub_category).closest('ul').addClass('in');
			$('.'+sub_category).find('a:first').css('color', '#AD3B39');
		}

		if(sub_sub_category) {
			$('.'+sub_sub_category).closest('ul').addClass('in');
			$('.'+sub_sub_category).find('a:first').css('color', '#AD3B39');
		}
	});

	function categoryToggle(item)
	{
		item.toggleClass('icon-plus icon-minus');
		// item.closest('li').find('a:first').addClass('custom-active');
		item.closest('li').find('a:first').css('color', '#AD3B39');
	}

</script>