accounts/urls.py
from django.urls import path, include
from .import views

app_name = 'accounts'

urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('', views.MyAccount.as_view(), name='myAccount'),
    path('login/', views.LoginView.as_view(), name='loginView'),
    # path('signin/', views.LoginView.as_view(), name='loginView'),
    path('signup/', views.Signup.as_view(), name='signup'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about-us/', views.AboutView.as_view(), name='aboutView'),
	path('contact/', views.ContactView.as_view(), name='contactView'),
	path('faqs/', views.FaqView.as_view(), name='faqView'),
    path('products/', include('products.urls')),
    path('account/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "House Of Faith"
admin.site.site_title  = "House Of Faith Admin Portal"

products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('add-to-wishlist/', views.addToWishlist.as_view(), name='addToWishlist'),
    path('get-product/', views.getProduct.as_view(), name='getProduct'),
    path('add-to-cart/', views.addToCart.as_view(), name='addToCart'),
    path('remove-from-cart/', views.removeFromCart.as_view(), name='removeFromCart'),
    path('place-order/', views.placeOrder.as_view(), name='placeOrder'),
    path('detail/<str:product_slug>/', views.ProductDetail.as_view(), name='productDetailView'),
    path('<str:category_slug>/', views.ProductView.as_view(), name='productView'),
    path('<str:category_slug>/<str:sub_category_slug>/', views.ProductView.as_view(), name='productView'),
    path('<str:category_slug>/<str:sub_category_slug>/<str:sub_sub_category_slug>/', views.ProductView.as_view(), name='productView'),
]

app/templates/about-us.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	{{ page_title | title }}
{% endblock %}

{% block body %}
<!-- Main Content -->
	<div class="page-container" id="PageContainer">
		<main class="main-content" id="MainContent" role="main">
			<section class="heading-content">
				<div class="heading-wrapper">
					<div class="container">
						<div class="row">
							<div class="page-heading-inner heading-group">
								<div class="breadcrumb-group">
									<div class="breadcrumb clearfix">
										<span>
											<a href="{% url 'home' %}" title="{{ mother_title | title }}"><span><i class="fa fa-home"></i></span></a>
										</span>
										<span class="arrow-space"></span>
										<span>
											<a title="{{ page_title | title }}"><span>{{ page_title | title }}</span></a>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section class="page-content">
				<div class="page-wrapper">
					<div class="container">
						<div class="row">
							<div class="page-inner">
								<div id="shopify-section-about-template" class="shopify-section">
									<div class="about-content">
										<div class="introduction_layout">
											<div class="introduction_inner">
												<div class="page_title">
													<h2 class="title">
														<span class="first">About</span>
														<span class="last"> {{ mother_title | title }}</span>
													</h2>
													{% if cis %}
													<p class="caption">{{ cis.first.aboutFirst | safe }}</p>
													{% endif %}
												</div>
												{% if cis %}
												<div class="introduction_content">
													<img src="{{ cis.first.images.url }}" alt="Dynamic">
													<div class="introduction_description">
														<p class="italics">{{ cis.first.aboutScond | safe }}</p>
													</div>
												</div>
												{% endif %}
											</div>
										</div>
										<div class="team_layout">
											<div class="page_title">
												<h2 class="title">
													<span class="first">Our</span>
													<span class="last"> {{ mother_title | title }}</span>
													<span class="first"> Team</span>
												</h2>
											</div>
											<div class="team_inner">
												<div class="team_content">
													{% if oats %}
													{% for oat in oats %}
													<div class="team_item col-sm-4">
														<div class="item_avatar">
															<img src="{{ oat.images.url }}" alt="">
														</div>
														<div class="item_content">
															<p class="item_name">{{ oat.name }}</p>
															<p class="item_position">{{ oat.designation }}</p>
															<p class="item_description">{{ oat.bioAP }}</p>
														</div>
													</div>
													{% endfor %}
													{% endif %}
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</main>
	</div>
{% endblock %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">

      <title>
        {% block title %}

        {% endblock %}
      </title>

      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Playball:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Bitter:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all">
      <!-- Bootstrap Dropdown Hover CSS -->
      <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap-dropdownhover.min.css' %}" rel="stylesheet">
      <!-- End Of Bootstrap Dropdown Hover CSS -->
      <link href="{% static 'css/fonts.googleapis.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/icon-font.min.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/social-buttons.scss.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/cs.styles.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/font-icon.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/cs.animate.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/slideshow-fade.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/animations.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/themepunch.revolution.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/jquery.fancybox.scss.css' %}" rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'css/spr.css' %}" rel="stylesheet" type="text/css" media="all">

      <script type="text/javascript">

          function getCookie(name) {
              var cookieValue = null;
              if (document.cookie && document.cookie !== '') {
                  var cookies = document.cookie.split(';');
                  for (var i = 0; i < cookies.length; i++) {
                      var cookie = cookies[i].trim();
                      // Does this cookie string begin with the name we want?
                      if (cookie.substring(0, name.length + 1) === (name + '=')) {
                          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                          break;
                      }
                  }
              }
              return cookieValue;
          }

          function uuidv4() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
              var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
              return v.toString(16);
            });
          }

          let device = getCookie('device')

          if (device == null || device == undefined){
              device = uuidv4()
          }

          document.cookie ='device=' + device + ";domain=;max-age=31536000;path=/"

      </script>

    </head>

    {% if home_title == 'house of faith' %}
      <body class="index-template fastfood_1">
    {% else %}
      <body class="fastfood_1">
    {% endif %}

    <!-- Navbar -->
    {% include 'navbar.html' %}

    <div class="fix-sticky"></div>

    {% block body %}

    {% endblock %}

    <!-- Footer -->
    {% include 'footer.html' %}

    <!-- Modals -->
    {% include 'modals.html' %}

    <!-- Float right icon -->
    <div class="float-right-icon">
      <ul>
        <li>
          <div id="scroll-to-top" data-toggle="" data-placement="left" title="Scroll to Top" class="off">
            <i class="fa fa-angle-up"></i>
          </div>
        </li>
      </ul>
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap Dropdown Hover JS -->
    <script type="text/javascript" src="{% static 'js/bootstrap-dropdownhover.min.js' %}"></script>
    <!-- End Of Bootstrap Dropdown Hover JS -->
    <script type="text/javascript" src="{% static 'js/classie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/application-appear.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.themepunch.plugins.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cs.script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.currencies.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.zoom.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/linkOptionSelectors.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/social-buttons.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.gmap.min.js' %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSxX2Un4CjYcWVyA3FOjBNcrVC1hlervk"></script>
  </body>
</html>

app/templates/footer.html
{% load static %}

<footer class="footer">
  <div id="shopify-section-theme-footer" class="shopify-section">
    <section class="footer-information-block clearfix"> <!-- style="background-image:  url(/static/images/bg_footer.png);" -->
      <div class="container">
        <div class="row">
          <div class="footer-information-inner">
            <div class="footer-information-content">
              <div class="information-item col-sm-4 not-animated" data-animate="fadeInUp" data-delay="100">
                <div class="about-content">
                  <div class="logo-footer">
                    <img src="{% static "images/HouseOfFaith.png" %}" style="height: 90px; margin-top: 30px;" alt="House Of Faith"/>
                  </div>
                  {% if cis %}
                  <!-- <div class="about-caption">
                    {{ cis.first.aboutFirst | safe | truncatewords:10 }}
                  </div> -->
                  {% endif %}
                  {% if cis %}
                  <div class="about-contact">
                    <div class="item">
                      <span class="cs-icon icon-marker"></span>
                      <address>{{ cis.first.address }}</address>
                    </div>
                    <div class="item">
                      <span class="cs-icon icon-phone"></span>
                      {{ cis.first.phone }}
                    </div>
                    <div class="item">
                      <span class="cs-icon icon-mail"></span>
                      {{ cis.first.email }}
                    </div>
                  </div>
                  {% endif %}
                </div>
              </div>

              <div class="blog-group col-sm-4 not-animated" data-animate="fadeInUp" data-delay="200">
                <h5 class="footer-title">New Products</h5>
                <div class="blog-content">
                  {% for product in latest_products %}
                    {% if product.status == True %}
                    {% if forloop.counter <= 3  %}
                    <div class="blogs-item">
                      <div class="blogs-left">
                        <a class="blogs-img" href="{% url 'products:productDetailView' product.slug %}">
                          <img src="{{ product.product_image.first.image_path }}" alt="{{ product.title }}" />
                        </a>
                      </div>
                      <div class="blogs-right">
                        <a href="{% url 'products:productDetailView' product.slug %}" class="blogs-title clearfix">{{ product.title }}</a>
                      </div>
                    </div>
                    {% endif %}
                    {% endif %}
                  {% endfor %}
                </div>
              </div>

              <div class="social-payment-item col-sm-4 not-animated" data-animate="fadeInUp" data-delay="300">
                <h5 class="footer-title">Follow Us</h5>
                <div class="social-content">
                  <div class="social-caption">
                    <a href="https://www.facebook.com/houseoffaithbd/" class="icon-social facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://twitter.com/HouseOfFaith9/" class="icon-social twitter"><i class="fa fa-twitter"></i></a>
                    {# <a href="https://plus.google.com/+shopify" class="icon-social google-plus"><i class="fa fa-google-plus"></i></a> #}
                    <a href="https://www.linkedin.com/in/house-of-faith-483b331b7/" class="icon-social pinterest"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.instagram.com/houseoffaith20/" class="icon-social instagram"><i class="fa fa-instagram"></i></a>
                    <a href="https://www.youtube.com/channel/UCw3T3GLoi8a_H8syT_wKjFg/" class="icon-social youtube"><i class="fa fa-youtube"></i></a>
                  </div>
                </div>
                <div class="payment-content ">
                  <h5 class="footer-title">Payment Methods</h5>
                  <div class="payment-caption">
                    <img src="{% static "images/bKash.png" %}">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="copy-right clearfix">
      <div class="copy-right-wrapper">
        <div class="copy-right-inner">
          <div class="footer_links">
            <ul>
              {% if user.is_authenticated %}
              <li><a href="{% url 'home' %}" title="Home">Home</a></li>
              <li><a href="{% url 'aboutView' %}" title="About Us">About Us</a></li>
              <li><a href="{% url 'faqView' %}" title="Faq">Faq</a></li>
              <li><a href="{% url 'contactView' %}" title="Contact">Contact</a></li>

              {% for category in categories %}
                {% for sub_category in category.product_sub_category.all %}
                  {% if forloop.counter <= 3 %}
                    <li>
                      <a href="{% url 'products:productView' category.slug sub_category.slug %}" title="{{ sub_category.name }}">{{ sub_category.name }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
              {% endfor %}

              {% for category in categories %}
                {% for sub_category in category.product_sub_category.all %}
                  {% for s_s_category in sub_category.product_sub_sub_category.all %}
                  {% if forloop.counter <= 3 %}
                    <li>
                      <a href="{% url 'products:productView' category.slug sub_category.slug s_s_category.slug %}" title="{{ s_s_category.name }}">{{ s_s_category.name }}</a>
                    </li>
                  {% endif %}
                  {% endfor %}
                {% endfor %}
              {% endfor %}

              {% else %}
              <li><a href="{% url 'home' %}" title="{{ mother_title | title }}">Home</a></li>
              <li><a href="{% url 'aboutView' %}" title="About Us">About Us</a></li>
              <li><a href="{% url 'faqView' %}" title="Faq">Faq</a></li>
              <li><a href="{% url 'contactView' %}" title="Contact Us">Contact Us</a></li>

              {% for category in categories %}
                {% for sub_category in category.product_sub_category.all %}
                  {% if forloop.counter <= 3 %}
                    <li>
                      <a href="{% url 'products:productView' category.slug sub_category.slug %}" title="{{ sub_category.name }}">{{ sub_category.name }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
              {% endfor %}

              {% for category in categories %}
                {% for sub_category in category.product_sub_category.all %}
                  {% for s_s_category in sub_category.product_sub_sub_category.all %}
                  {% if forloop.counter <= 3 %}
                    <li>
                      <a href="{% url 'products:productView' category.slug sub_category.slug s_s_category.slug %}" title="{{ s_s_category.name }}">{{ s_s_category.name }}</a>
                    </li>
                  {% endif %}
                  {% endfor %}
                {% endfor %}
              {% endfor %}

              <li><a href="{% url 'accounts:loginView' %}" title="Login">Login</a></li>
              <li><a href="{% url 'accounts:signup' %}" title="Register">Register</a></li>
              {% endif %}
            </ul>
          </div>
          <div class="footer_copyright">Copyright &copy; 2020 <a href="" title="{{ mother_title | title }}">{{ mother_title | title }}</a>. All Rights Reserved</div>
        </div>
      </div>
    </section>
  </div>
</footer>

app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	{{ home_title | title }}
{% endblock %}

{% block body %}
<!-- Main Content -->
<div class="page-container" id="PageContainer">
	<main class="main-content" id="MainContent" role="main">

		<!-- BEGIN content_for_index -->
		<!-- Default Slide (Dynamic)-->
		<div id="shopify-section-1507179171162" class="shopify-section index-section index-section-slideshow">
			<div data-section-id="1507179171162" data-section-type="slideshow-section">
				<section class="home-slideshow-layout">
					<div class="home-slideshow-wrapper">
						<div class="group-home-slideshow">
							<div class="home-slideshow-inner">
								<div class="home-slideshow-content slideshow_1507179171162">
									<ul>
										{% for slider in d_slides %}
										<li data-transition="random-static" data-masterspeed="2000" data-saveperformance="on">
											<img src="{{ slider.image.url }}" alt="" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
											{% if forloop.counter == 1 or forloop.counter == 2 %}
											<div class="slideshow-caption position-left transition-fade">
												<div class="group">
													<a href="{{ slider.url }}">
														<img src="{{ slider.PNG.url }}" alt=""/>
													</a>
													<a class="_btn" href="{{ slider.url }}">Buy now</a>
												</div>
											</div>
											{% else %}
											<div class="slideshow-caption position-middle transition-fade">
												<div class="group">
													<a href="{{ slider.url }}">
														<img src="{{ slider.PNG.url }}" alt=""/>
													</a>
													<a class="_btn" href="{{ slider.url }}">Find out more!</a>
												</div>
											</div>
											{% endif %}
										</li>
										{% endfor %}
									</ul>
									<div class="tp-bannertimer"></div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>

		<!-- Carousel Slide (Dynamic)-->
		<div id="shopify-section-1509012157667" class="shopify-section index-section index-section-banner">
			<div data-section-id="1509012157667" data-section-type="banner-section">
				<section class="home-banslider-layout">
					<div class="container">
						<div class="row">
							<div class="home-banslider-inner">
								<div class="home-banslider-content">
									{% for slider in c_slides %}
									<div class="banslider-item not-animated" data-animate="zoomIn" data-delay="100">
										<a href="{{ slider.url }}">
											<img src="{{ slider.image.url }}" alt="" title="">
										</a>
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>

		<div id="shopify-section-1509012338884" class="shopify-section index-section index-section-welcome">
			<div data-section-id="1509012338884" data-section-type="welcome-section">
				<section class="home-welcome-layout not-animated" data-animate="zoomIn" data-delay="200">
					<div class="container">
						<div class="row">
							{% if home %}
							<div class="home-welcome-inner">
								<h2 class="page-title">{{ home.first.welcome_Message }}</h2>
								<div class="home-welcome-content">
									<span class="welcome-caption">{{ home.first.aboutCompany | safe }}</span>
									<img class="welcome-banner" src="{{ home.first.image_One.url }}" alt="" title="">
								</div>
							</div>
							{% endif %}
						</div>
					</div>
				</section>
			</div>
		</div>

		<!-- Categorical Products (Dynamic)-->
		{% for category in product_categories %}
		<div class="shopify-section index-section index-section-product">
			<div data-section-id="1509012370397" data-section-type="product-section">
				<section class="home-product-layout">
					<div class="container">
						<div class="row">
							<div class="banner-product-title not-animated" data-animate="fadeInUp" data-delay="200" style="background-image:  url({{ category.categoryImage.url }});">
								<div class="title-content">
									<h2>{{ category.name }}</h2>
								</div>
							</div>
							<div class="home-product-inner">
								<div class="home-product-content">
									{% for product in category.category_product.all %}
									{% if product.status == True %}
									{% if forloop.counter <= 16 %}
									<div class="content_product col-sm-3 not-animated" data-animate="fadeInUp" data-delay="100">
										<div class="row-container product list-unstyled clearfix product-circle">
											<div class="row-left">
												<a href="{% url 'products:productDetailView' product.slug %}" class="hoverBorder container_item">
													<div class="hoverBorderWrapper">
														<img src="{{ product.product_image.first.image_path }}" class="img-responsive front" alt="">
														<div class="mask"></div>
													</div>
												</a>
												<div class="hover-mask">
													<div class="group-mask">
														<div class="inner-mask">
															<div class="group-actionbutton">
																<ul class="quickview-wishlist-wrapper">
																	<li class="wishlist">
																		<a title="Add To Wishlist" onclick="addToWishlist($(this), '{{ product.slug }}');"><span class="cs-icon icon-heart"></span></a>
																	</li>
																	<li class="quickview hidden-xs hidden-sm">
																		<div class="product-ajax-cart">
																			<span class="overlay_mask"></span>
																			<div data-handle="coke" data-target="#quick-shop-modal" class="quick_shop" data-toggle="modal">
																				<a onclick="getProduct($(this), '{{ product.slug }}');"><span class="cs-icon icon-eye"></span></a>
																			</div>
																		</div>
																	</li>
																</ul>
															</div>
															<form action="javascript:void(0);" method="post" onsubmit="addToCart($(this))">
																<div class="effect-ajax-cart">
																	<input type="hidden" value="{% if user.is_authenticated %} {{ user.id }} {% endif %}" id="user_id">
																	<input type="hidden" value="{{ product.id }}" id="product_id">
																	<input type="hidden" value="1" id="quantity">
																	<button class="_btn add-to-cart" data-parent=".parent-fly" type="submit" name="add" title="Add To Cart"><span class="cs-icon icon-cart"></span>Add to cart</button>
																</div>
															</form>
														</div>
														<!--inner-mask-->
													</div>
													<!--Group mask-->
												</div>
												{% if product.product_offer %}
												{% for product_offer in product.product_offer.all %}
												<div class="product-label">
													<div class="label-element deal-label">
														<span>{{ product_offer.product_offer.firstWord }}</span>
													</div>
													<div class="label-element hotting-label">
														<span>{{ product_offer.amount | floatformat }}%</span>
													</div>
												</div>
												{% endfor %}
												{% endif %}
											</div>
											<div class="row-right animMix">
												<div class="rating-star">
													<span class="spr-badge" data-rating="5.0">
														<span class="spr-starrating spr-badge-starrating">
															<i class="spr-icon spr-icon-star" style=""></i>
															<i class="spr-icon spr-icon-star" style=""></i>
															<i class="spr-icon spr-icon-star" style=""></i>
															<i class="spr-icon spr-icon-star" style=""></i>
															<i class="spr-icon spr-icon-star" style=""></i>
														</span>
														<span class="spr-badge-caption">1 review</span>
													</span>
												</div>
												<div class="product-title"><a class="title-5" href="{% url 'products:productDetailView' product.slug %}">{{ product.title }}</a></div>
												<div class="product-price">
													{% if product.product_offer.all %}
													<span class="price_sale">
														<span class="money" data-currency-usd="{{ product.stock_product.first.after_offer_unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.after_offer_unit_price }}</span>
													</span>
													<del class="price_compare">
														<span class="money" data-currency-usd="{{ product.stock_product.first.unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.unit_price }}</span>
													</del>
													{% else %}
													<span class="price_sale">
														<span class="money" data-currency-usd="{{ product.stock_product.first.unit_price }}" data-currency="BDT">৳ {{ product.stock_product.first.unit_price }}</span>
													</span>
													{% endif %}
												</div>
											</div>
										</div>
									</div>
									{% endif %}
									{% endif %}
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
		{% endfor %}

		<div id="shopify-section-1509012518613" class="shopify-section  index-section index-section-banner">
			<div data-section-id="1509012518613" data-section-type="banner-section">
				<section class="home-banner-layout not-animated" data-animate="zoomIn" data-delay="200">
					<div class="container">
						<div class="row">
							<div class="home-banner-inner">
								<div class="home-banner-content">
									{% if home %}
									<a class="banner-image" href="{{ home.first.url }}">
										<img src="{{ home.first.image_Two.url }}">
									</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</main>
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">

	function addToWishlist(item, product_slug) {
		var url = "{% url 'products:addToWishlist' %}";

        var data = {
            product_slug: product_slug,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        }

        // console.log(data);

        $.post(url, data, function(response) {
            // var product = JSON.parse(response);
            // console.log(product);

            // load modal data
            $('#modal-wishlist-body').html(response);

            // show modal
            $('#modal-wishlist').modal('show');
        });
	}

	function getProduct(item, product_slug)
	{
		var url = "{% url 'products:getProduct' %}";

        var data = {
            product_slug: product_slug,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        }

        // console.log(data);

        $.post(url, data, function(response) {
            // var product = JSON.parse(response);
            // console.log(product);

            // load modal data
            $('#quick-shop-modal-body').html(response);

            // show modal
            $('#quick-shop-modal').modal('show');
        });
	}

	function maxQtyCheck(item)
	{
		var qty = parseInt(item.val());
		var max_qty = parseInt($('#max-quantity').val());

		if (qty > max_qty)
		{
			alert('Sorry, limit exceeded!');
			item.val(max_qty);
		}
	}

	function addToCart(item)
	{
        var user_id = item.find('#user_id').val();
        var product_id = item.find('#product_id').val();
        var quantity = item.find('#quantity').val();
        var url = "{% url 'products:addToCart' %}";

        var data = {
        	user_id: user_id,
        	product_id: product_id,
        	quantity: quantity,
        	csrfmiddlewaretoken: '{{ csrf_token }}'
        }

		$.post(url, data, function(response) {
			console.log(response);
		});
    }

</script>

{% endblock %}